language: ruby
rbenv:
- 2.3.1
- jruby
- rbx-2
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
services:
- postgresql
before_script:
# - psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script: bundle exec rspec spec
env:
  global:
  - secure: kzCZyxiUtLpYGxa0R/wzsZwff8PH9Na/tqMNUGb7WVjEpT6rnDcOTrVsMX4iRxgBw9TJQ2bSQjGy3RTvxm6XuhceaU3JRGyvUzEUqXXxPXw+tLvl9UM/T8LPlvLG+gADoMBaoKSnBvr2HmQRP3SkXlZbtMlw1K2d4EdlJSdkT+/DWzgE5PhuQKRNJKBAk96xFHpetTqc0jWiojfEJyHzpw6FkA11EgUdx0r2/PPb8cGxd32Ml+04X7tcwzyf/kezXaTpz7nRI4OGKMk7LedLKwxhvyQxwZzafwZXJxM1eaFUNwJcdEXe/u+khd3Mi53qbfxp6vVGwwUcRmrWwQY90thbBcbP/EfKpUxRYT/xy6yJTrkxteVqlAcq6L6iSVGleSZG2l6yyV10p5wh0M4FbBLiyN6KcwTYQNVZYjkmmp43gQuZnW8Ur1UnJHXamONPgOMVBbm7h5MqfQLI9876HNkgi9wmJXxheA7CWPybIuFl5bNHRuOhcduFrK5hEbumg/9UzxwSxYXdzrWLBNndylMuaibZq1pEJi+yyo5XSMEGXIePA7ZE3cM/DrMSHSIct5Zn9+Lni4C+bjoJAlGcJ+eYcRhkvW1iCqm50MLcB/m1e3hhgViVz7fd5wSshlqzcrP87tGOQ5lqBm7nBkYFcnaLI+32vSscGuWSYJrcJvo=
  - secure: YuNb6Cf/mfVVM5pKum6qlcBvwB2p81Zp7qxSwPLdp2xbHsZWiUJQsOIHRZ+xOqXGer9MVriLJGFHlSRCaVJbPFJet9TfOBujd7CXVedeIKicbLcht01AGWA/Y4j1EUqDZ4RLVBnQ3ncGuyfg+9/TiL73tnPrwXsWQhGTHCwfioFyw1GxgGy3NeMGUIZWp7fyo60TnJ6rZBqhQL9W0V4/9+qwmmP5DzSj+k2gbRj6MVNXTOuP6JjDWUQOR4AOhF8i1jqPdCcPjXOV65/GLybCHLJB+u9R/cr/VrTn59zyIoKyCgxTllu0TrUtTLYUwAZEVw8ytm2laDAbpt3hfoOZnyqKTEbnvj8+iS01ycrSlYpfBWzTIz/uzK/nxLtfoQK979ODPjIPJiLJhja96xAXVSr7vnLfWYayL1jiZInwFzn61IyWDAJY2/ED1PSQnGF+ueOwAfv62wV1zso7j6+vVLxBe1xLkJQCwGirhTC5L/cvShILFX3LUcm2a235xkOjOQBfUTM7EdvW5GUw2lraxTc7lvU+n1kY3kmSZh/IUW6+/2Y19hE9KCKYuzWdbqSOKYFbGU8gHyRvPViH5qc6QizJ0gP504Df55STr9pApy4E1yN9F5JiiWM45BdotzJJA8dpOisKzyCqTwzj8v1JirS5KL9fEJozYa+etLWfAqg=
  - secure: oqbdpb8EoRCeV37KPuh8aCFL2Aizhj4M3Jr+qDDWe53r0vK3i/gryXIn/e8G57nq9lqT/UGM8hLDXqifpH61RYbGc1dLUeTHGB96rTfrE2b/KRMWTIknRjoVDhvxVvf1gMnYWeLJUOIIr3tcPsCG0BsXASzgLhDw9uSwTpr/X7ansZKSBhiRSzYtU9amwuf6EYw4d4bnIwQdoq3UAGNApwWSC6HjttvKgagNtNmJhgosYHydkE+vnUryue/fzaRzisvoC5cd05xyN0vs56f4jhfRCMYiW+pk5kBxEn8f7KgApQ+fKI3txb8bf4UTrepx/vRRqFN4HT1HQ3PMi5srwlLbdV2zbOyOFmAjjzeiospHYs8NpvQQptNNCIRbVnGjZoUyx/WIuwK6h2Vr8R705eE2+PIxxRihTttuAj1KsqFeSooDjWYpp3HGvWlOQlb3aDYcq0ZSK33bHqnWZuLQ9q/QgFnHyMxaWE4ilhvDKz3Nj2sMeZgKjLm0U+SW09fCcaXGQr4ddOSvrQB86XQaVM59jVYFH/uiefHrq23/Oso6THicqYSjChVZWvmbae7L3C/duMaMrGKXa8qbcudM7wWmfPLng/6av/oqdE23GSx7Fwn4UrHRi7EXSmBhYQeEFnkwRWPje+AeWMSPcfqVxeLMaa/85mfyXL+V24WM0Ks=
